name: Moodle Plugin CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [moodle-plugin-ci]

jobs:
  moodle-plugin-ci:
    uses: moodle-an-hochschulen/moodle-workflows/.github/workflows/moodle-plugin-ci.yml@main
    with:
      moodle-core-branch: MOODLE_405_STABLE
      plugin-dependencies: |
        vadimonus/moodle-quizaccess_onesession,master
